export const trainsData = [
    // Express Category
    { id: 'greenline', category: 'express', name: 'Green Line Express', route: 'Karachi ⟷ Islamabad', cities: ['Karachi', 'Hyderabad', 'Rohri', 'Bahawalpur', 'Khanewal', 'Lahore', 'Rawalpindi', 'Islamabad'], slides: ['/images/greenline_7.webp'], fares: [{class:"AC Parlor",price:"Rs. 12,250"},{class:"Economy",price:"Rs. 6,150"},{class:"AC Business",price:"Rs. 13,950"},{class:"AC Standard",price:"Rs. 11,150"}], stats: { punctuality: '95%', cleanliness: 5, food: 4, behavior: 5 }, amenities: ['wifi', 'charging', 'bedding', 'dining', 'ac'], composition: { parlor: '01', business: '06', standard: '06', economy: '05', diningcar: '01' } },
    { id: 'shalimar', category: 'express', name: 'Shalimar Express', route: 'Karachi ⟷ Lahore', cities: ['Karachi', 'Hyderabad', 'Faisalabad', 'Lahore'], slides: ['/images/shalimar_8.webp'], fares: [{class:"AC Parlor",price:"Rs. 10,700"},{class:"Economy",price:"Rs.4,010"},{class:"AC Business",price:"Rs. 11,400"},{class:"AC Standard",price:"Rs. 8,700"}], stats: { punctuality: '95%', cleanliness: 5, food: 5, behavior: 5 }, amenities: ['wifi', 'charging', 'bedding', 'dining', 'ac'], composition: { parlor: '01', business: '01', standard: '02', economy: '11', diningcar: '01' } },
    { id: 'karakoram', category: 'express', name: 'Karakoram Express', route: 'Karachi ⟷ Lahore', cities: ['Karachi', 'Hyderabad', 'Rohri', 'Bahawalpur', 'Khanewal', 'Toba Tek Singh', 'Faisalabad', 'Lahore'], slides: ['/images/karakoram_express_train_rake.webp'], fares: [{class:"AC Business",price:"Rs. 10,500"},{class:"Economy",price:"Rs. 4,750"},{class:"AC Standard",price:"Rs. 8,300"}], stats: { punctuality: '90%', cleanliness: 4, food: 3, behavior: 3 }, amenities: ['ac'], composition: { business: '02', economy: '11', standard: '02' } },
    { id: 'pakbusiness', category: 'express', name: 'Pak Business Express', route: 'Karachi ⟷ Lahore', cities: ['Karachi', 'Hyderabad', 'Nawabshah', 'Rohri', 'Rahim Yar Khan', 'Bahawalpur', 'Khanewal', 'Chicha Watni', 'Sahiwal', 'Raiwind', 'Kot lakhpat', 'Lahore'], slides: ['/images/business_1.webp'], fares: [{class:"AC Standard",price:"Rs. 8,700"},{class:"Economy",price:"Rs. 5,350"}], stats: { punctuality: '90%', cleanliness: 5, food: 5, behavior: 5 }, amenities: ['wifi', 'charging', 'bedding', 'dining', 'ac'], composition: { standard: '04', economy: '11', diningcar: '01' } },
    { id: 'allamaiqbal', category: 'express', name: 'Allama Iqbal Express', route: 'Karachi ⟷ Sialkot', cities: ['Karachi', 'Hyderabad', 'Rohri', 'Khanewal', 'Sahiwal', 'Lahore', 'Sialkot'], slides: ['/images/allama_1.webp'], fares: [{class:"AC Standard",price:"Rs. 6,800"},{class:"Economy",price:"Rs. 3,500"}], stats: { punctuality: '75%', cleanliness: 3, food: 3, behavior: 4 }, amenities: ['charging', 'dining', 'ac'], composition: { business: '04', economy: '10' } },
    { id: 'sukkur', category: 'express', name: 'Sukkur Express', route: 'Karachi ⟷ Jacobabad', cities: ['Karachi', 'Hyderabad', 'Rohri', 'Sukkur', 'Shikarpur', 'Jacobabad'], slides: ['/images/coming_soon.avif'], fares: [{class:"AC Sleeper",price:"Rs. 6,500"},{class:"Economy",price:"Rs. 1,700"},{class:"AC Standard",price:"Rs. 3,200"},{class:"AC Business",price:"Rs. 4,150"}], stats: { punctuality: '65%', cleanliness: 4, food: 3, behavior: 3 }, amenities: ['charging', 'dining', 'ac'], composition: {sleeper: '01', business: '01', standard: '02', economy: '12' } },
    { id: 'karachi', category: 'express', name: 'Karachi Express', route: 'Karachi ⟷ Lahore', cities: ['Karachi', 'Hyderabad', 'Nawabshah', 'Rohri', 'Bahawalpur', 'Multan', 'Khanewal', 'Sahiwal', 'Okara', 'Raiwind', 'Kot lakhpat', 'Lahore'], slides: ['/images/coming_soon.avif'], fares: [{class:"AC Sleeper",price:"Rs. 14,850"},{class:"Economy",price:"Rs. 5,000"},{class:"AC Standard",price:"Rs. 8,700"},{class:"AC Business",price:"Rs. 11,550"}], stats: { punctuality: '85%', cleanliness: 4, food: 4, behavior: 4 }, amenities: ['charging', 'dining', 'ac'], composition: {sleeper: '02', business: '01', standard: '02', economy: '12' } },

    // Mail Category
    { id: 'bolanmail', category: 'mail', name: 'Bolan Mail', route: 'Karachi ⟷ Quetta', cities: ['Karachi', 'Larkana', 'Sibi', 'Quetta'], slides: ['/images/coming_soon.avif'], fares: [{class:"AC Sleeper",price:"Rs. 13,000"},{class:"Economy",price:"Rs. 4,000"}], stats: { punctuality: '82%', cleanliness: 3, food: 2, behavior: 3 }, amenities: ['dining'], composition: {sleeper: '01', economy: '10'} },    
    { id: 'khybermail', category: 'mail', name: 'Khyber Mail', route: 'Karachi ⟷ Peshawar', cities: ['Karachi', 'Multan', 'Lahore', 'Peshawar'], slides: ['/images/coming_soon.avif'], fares: [{class:"AC Sleeper",price:"Rs. 13,000"},{class:"Economy",price:"Rs. 4,000"}], stats: { punctuality: '82%', cleanliness: 3, food: 3, behavior: 4 }, amenities: ['ac', 'dining'], composition: {sleeper: '02', business: '01', economy: '12'} },    

    // Railcar Category
    { id: 'subakkharam', category: 'railcar', name: 'Subak Kharam', route: 'Lahore ⟷ Rawalpindi', cities: ['Lahore', 'Gujranwala', 'Jhelum', 'Rawalpindi'], slides: ['/images/coming_soon.avif'], fares: [{class:"AC Business",price:"Rs. 2,100"},{class:"Economy",price:"Rs. 1,100"}], stats: { punctuality: '98%', cleanliness: 5, food: 4, behavior: 5 }, amenities: ['ac', 'charging'], composition: {business: '03', economy: '08'} },
    { id: 'musapak', category: 'railcar', name: 'Musa Pak Express', route: 'Lahore ⟷ Multan', cities: ['Multan','Khanewal','Sahiwal','Lahore'], slides: ['/images/coming_soon.avif'], fares: [{class:"AC Business",price:"Rs. 2,300"},{class:"Economy",price:"Rs. 1,200"},{class:"AC Parlor",price:"Rs. 2,400"}], stats: { punctuality: '90%', cleanliness: 3, food: 3, behavior: 4 }, amenities: ['ac', 'charging'], composition: {parlor: '01', business: '02', economy: '08'} },

    // Local Category
    { id: 'mehran', category: 'local', name: 'Mehran Express', route: 'Karachi ⟷ Mirpur Khas', cities: ['Karachi', 'Hyderabad', 'Mirpur Khas'], slides: ['/images/mehran_1.webp'], fares: [{class:"Economy",price:"Rs. 800"}], stats: { punctuality: '70%', cleanliness: 2, food: 1, behavior: 3 }, amenities: [], composition: {economy: '08'} }
];